// app/layout.js یا app/layout.tsx

import { Inter } from "next/font/google";
import "./globals.css";

// فقط فونت Inter رو وارد می‌کنیم
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata = {
  title: "Fund For Fund",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
