// app/layout.js یا app/layout.tsx

import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/shared/footer/footer";
import Navbar from "./components/shared/navbar";
import { AuthProvider } from "../context/AuthContext";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata = {
  title: "Fund For Fund",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <AuthProvider>

          {children}

        </AuthProvider>
      </body>
    </html>
  );
}
